In [12]:
import numpy as np

a = np.random.randn(5)

In [31]:
print(a)

[ 0.77222271 -0.21586847 -0.24033548  0.32021674  1.16532263]


In [33]:
print(a.shape)

(5,)


In [36]:
print(a.T)

[ 0.77222271 -0.21586847 -0.24033548  0.32021674  1.16532263]


In [40]:
print(np.dot(a, a.T))

2.16120383075741


In [44]:
a = np.random.randn(5,1)
print(a)

[[-0.09479524]
 [ 0.82277289]
 [ 1.45512251]
 [ 0.83389012]
 [ 1.53586965]]


In [46]:
print(a.T)

[[-0.09479524  0.82277289  1.45512251  0.83389012  1.53586965]]


In [51]:
print(np.dot(a,a.T))

[[ 0.00898614 -0.07799495 -0.13793868 -0.07904881 -0.14559313]
 [-0.07799495  0.67695524  1.19723536  0.68610219  1.26367192]
 [-0.13793868  1.19723536  2.11738151  1.21341228  2.23487849]
 [-0.07904881  0.68610219  1.21341228  0.69537273  1.28074653]
 [-0.14559313  1.26367192  2.23487849  1.28074653  2.35889558]]


In [52]:
print(np.dot(a.T,a))

[[5.85759119]]
